### ISSUE TITLE
Updates for Aleph and OCLC Records

### ISSUE THREAD

**Issue by EthanDF** [EthanDF/CAWG_MARC_Notes#1]
I need something to make the updating of the Aleph and OCLC records more robust so that as the update files are cycling through, they're not adding duplicates to records that are already in the table.

**Comment by aglerum** [comment]
Just now seeing this... not sure of the context. Is this in SQLite?

**Comment by EthanDF** [comment]
oh, it was just a note to self to remember to work on this next.

**Comment by aglerum** [comment]
Sorry, this is the first time I've been sent a GitHub notification. Still a
newbie 🙃

**Comment by EthanDF** [comment]
this is fixed
